#! /bin/bash
###############################################################################
# Copyright (c) 2009 Intuit, Inc.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.opensource.org/licenses/eclipse-1.0.php
# 
# Contributors:
#     Intuit, Inc - initial API and implementation
###############################################################################/

dir=$(dirname $0)
export CLASSPATH=${CLASSPATH}${CLASSPATH:+:}${dir}/\*
exec java -jar ${dir}/Ginsu-1.0.0-SNAPSHOT.jar -home ${dir} "$@"
